//
//  FirstChats.swift
//  ChitChat
//
//  Created by Alex Coundouriotis on 4/20/23.
//

import Foundation

class FirstChats {
    
    private static let firstChats: [String] = [
        "How may I help?",
        "How can I help you?",
        "Anything I can help you with?",
        "How may I help?",
        "Here's a tip... I work better with more detail. A sentence or two works, but you can give me paragraphs or full essays. Try it out!",
        "I'm pretty original, but use what I write as inpsiration.",
        "Hey!",
        "Hello, how can I help?",
        "Hi there, how can I help?",
        "Hello!",
        "Beep Boop",
        "How are you feeling?",
        "How are you today?",
        "Are you doing well?",
        "I'm great at writing essays!",
        "I'm great at writing poems!",
        "I'm great at writing lyrics!",
        "How are you doing today?",
        "Hey there, don't hesitate to throw at me complex projects or queries. I'm up for a challenge!",
//        "Is there a specific style of writing you'd prefer? Be sure to let me know - I can handle it!",
//        "Can't find the right words? Don't worry - just tell me your thoughts in simple terms, I'll help articulate them for you!",
        "Are you struggling with a creative block? Give me a starting point and I'll help you get the creative juices flowing!",
        "I'm here to assist you 24/7, so go ahead and reach out anytime you need!",
        "Thinking out-of-the-box can be my thing too. Send me something unconventional, let's see what we can do with it!",
        "Remember, the more specific you are with what you want, the better results I can provide!",
//        "Are we talking fact or fiction today? Either way, I’m here to help!",
//        "Need inspiration? Run me through your ideas and let's brainstorm together!",
//        "Unsure about your grammar? Fear not! You can count on me for proofreading and editing.",
//        "It’s okay to disagree with me. After all, the aim is to engage and evolve as we interact!",
//        "Want to learn something new today? Just ask me for fact-based information!",
        "For the best results, give me clear instructions. It helps me understand exactly what you're looking for!",
        "I can do more than just assist - I can entertain with a funny joke or a sweet poem whenever you need some cheering up!",
//        "Trying to learn a new language? I can help you with translation and vocabulary too!",
        "Are you feeling down? Tell me. Sometimes, it helps to just talk it out.",
//        "Feeling nostalgic? I can suggest some classic books or films for you to revisit!",
        "Good day, how can I assist you?",
        "Do you need help with your homework?",
        "What topic do you need assistance with?",
//        "Do you need help formatting your essay?",
        "Would you like me to generate a study schedule for you?",
//        "Would you like assistance with your upcoming science project?",
        "I'm effectively fluent in almost all academic subjects and multiple languages. Put me to test!",
//        "Ready with your coffee? Shall we dig into our next study chapter?",
//        "Exhausted? I can put together a relaxation routine, too!",
//        "If you're stuck with math, write out your problem and I can try to help.",
        "Look no further for your bot-driven, subject matter expert.",
//        "Would you like some flashcards? I can create them for you.",
//        "Need statistics help? Share the data set, and I'll crunch the numbers for you.",
//        "Studying for a vocabulary test? I can test your knowledge and help to bring it up a level.",
//        "Getting ready for a literature test? Share the reading, and I'll come up with some probing questions.",
//        "Preparing for a history exam? I can quiz you based on the main dates and events.",
//        "Would you like to practice an oral presentation? Dictate it to me, and I can offer feedback.",
//        "I can also help with brainstorming ideas for creative writing or research projects.",
//        "Having trouble understanding a science concept? I can break it down for you.",
//        "Trying to learn a new language? I can be your language partner.",
//        "Preparing for a Geography exam? I can test you on topography or locations.",
//        "Studying for a music exam? I can create note reading or listening exercises.",
//        "Need some motivation? I can send you motivational quotes or tips!",
//        "How about a study break? Let me recommend an engaging short activity.",
        "Did you know affirmations can enhance your studying ability? I can generate some for you.",
//        "Need clarity on a piece of literature? I can give you a rundown.",
//        "Let's work on your problem-solving skills today. Shall we?",
        "Shall I remind you to take short breaks? It's beneficial for your learning process.",
//        "Did you know that I can help improve your note-taking skills?",
//        "Having trouble focusing? Let me share some concentration exercises.",
//        "Practicing past exams can be very beneficial. Want me to generate some questions?",
//        "Need help with structuring your essay? I can guide you step by step.",
//        "Do you need assistance in remembering critical information? I can ingest it and quiz you!",
//        "Winding up? Don't forget to revise. I am here if you need help.",
//        "Need help managing your time? I can help you create a time-management plan.",
//        "Are you procrastinating? I can give you some anti-procrastination tips.",
//        "Do you want to learn speed reading? I can teach you!",
//        "Ready to solve some equations? Let's make math your friend, not foe.",
//        "Coded something? I can help you debug or optimize.",
//        "Need some coaching in a sports theory? Run it by me, let's explore it together.",
//        "Writing a science experiment report? Tell me what happened, and I can help with the rest.",
//        "Trying to memorize things for long term? I can implement spaced repetition techniques.",
//        "Do you want to improve your handwriting? Share with me a sample, I can provide constructive feedback.",
//        "Can't spell a term? Just spell it out phonetically, I'll correct it for you.",
//        "Writing an application or personal statement? I can help you make an impressive impact.",
//        "Need improvement in handwriting speed? Let's practice together with simple exercises!",
//        "Having trouble with Shakespearean language? I can help decode it.",
//        "Need to remember scientific names? I can turn it into a fun mnemonic for you.",
//        "Preparing for a mental math test? Let's work on some problems to speed up your calculations.",
//        "Want to know more about a historical event? I can provide detailed information.",
//        "Need a break? How about a quick, fun quiz?",
//        "Overwhelmed by assignments? Let's prioritize them together!",
//        "Need some motivation? I can share success stories related to your subject.",
//        "Studying for a spelling bee? I can create custom spelling lists for your practice.",
//        "Interpreting a piece of art? Express your thoughts, I can help you refine them.",
//        "Having trouble with a philosophical concept? I can explain it in layman's terms.",
//        "Learning a musical instrument? I can guide you on the theory part.",
//        "Need help balancing chemical equations? No worries! I'm here to help.",
//        "Trying to learn programming? I can answer your coding questions.",
//        "Feeling anxious about exams? I can suggest some stress-relieving techniques.",
//        "Studying in a noisy environment? I can recommend some focus songs.",
//        "Pulling an all-nighter? I can share some energy boosting food suggestions.",
//        "Feeling tired? Remember to rest, and I will remind you to get back to studies once you're refreshed.",
//        "Need help with punctuation? I can be your personal punctuation checker.",
//        "Preparing for a general knowledge quiz? I can share interesting facts from various domains.",
//        "Worked up with all the studying? How about some light riddles to lighten up the mood?",
//        "Learning a new concept? I can provide you with an outline to keep your learning structured.",
//        "Struggling with prepositions? I can set up some exercises to improve your grasp on them.",
//        "Need to revise for an upcoming test? I can generate topic-wise questions.",
//        "Trouble with a physics formula? Let's work on it together.",
//        "Stressed about deadlines? Share your schedule, I can remind you of upcoming ones.",
//        "Need to check some citations? I can verify the style and format.",
//        "Learning about nutrition? I can help with facts and figures.",
//        "Preparing a lesson plan? Share your syllabus, I can help generate an effective plan.",
//        "Need some assessment in English Literature? I can help with character analysis and themes.",
//        "Need help with essay citations? I can guide you with referencing styles.",
//        "Studying law? I can assist you in understanding legal terminologies.",
//        "Preparing for a job interview? I can help with some commonly asked questions.",
//        "Want to improve your vocabulary? I can suggest a 'word of the day'.",
//        "Frustrated with a complex algorithm? Let's decompose it step by step.",
//        "Trying to understand poetry? I can help with the feel and rhythm of it.",
//        "Need a new study strategy? I can recommend some effective study techniques tailored for you.",
//        "Looking for research paper ideas? I can suggest a few relevant to your field.",
//        "Do you get distracted often? I can share some ways to break free from distractions.",
//        "Thinking of improving your overall performance? I can help you out with sustainable study habits.",
//        "Challenged with Economics theories? I can help simplify them for you.",
//        "Revising for an upcoming test? I can help with flashcards for a quick overview.",
//        "Gearing up for a debate? I can help you with counter-arguments.",
//        "Need help with multiple choice questions? I can help you handle them with confidence.",
//        "Want to learn creative writing? I can guide you through the process with some prompts and tips."
    ]
    
    public static func getRandomFirstChat() -> String {
        return firstChats[Int.random(in: 0..<firstChats.count)]
    }
    
}
